title: Chaitanya Devarshi
logo: assests/img/imagee.png
# description: [LinkedIn](linkedin.com/in/chaitanya-devarshi-7339261b1)
# show_downloads: true
theme: jekyll-theme-minimal
include_search: true
social_links:
  linkedin: "https://www.linkedin.com/in/chaitanya-devarshi-7339261b1"

# # Basic Settings
# title: Chaitanya Devarshi
# logo: assets/img/image.png
# description: "Data Scientist | Software Engineer | Backend Developer"
# url: "https://your-github-username.github.io/your-repo-name"
# baseurl: "" # leave this empty if the site is at the root of the domain

# # Appearance and Theme Settings
# theme: jekyll-theme-minimal
# # show_downloads: true # Enable download buttons for files if needed
# include_search: true # Add search functionality to your site (requires plugins)
# paginate: 5 # Number of posts per page if you're including a blog section

# # Social Links (optional for easy access)
# social_links:
#   linkedin: "https://www.linkedin.com/in/chaitanya-devarshi-7339261b1"
#   github: "https://github.com/your-github-username"
#   twitter: "https://twitter.com/your-twitter-handle"
#   email: "mailto:your-email@example.com"

# # Navigation Links (helps structure the website navigation)
# nav_links:
#   - name: "Home"
#     url: "/"
#   - name: "Portfolio"
#     url: "/portfolio"
#   - name: "Blog"
#     url: "/blog"
#   - name: "Contact"
#     url: "/contact"

# # Plugins (for additional functionalities like SEO, analytics)
# plugins:
#   - jekyll-seo-tag # Adds SEO metadata
#   - jekyll-sitemap # Generates a sitemap for search engines
#   - jekyll-feed # Adds an RSS feed

# # SEO Settings
# seo:
#   title: "Chaitanya Devarshi - Portfolio"
#   description: "Explore Chaitanya Devarshi's projects in Data Science, Machine Learning, and Software Development."
#   keywords: "Data Science, Software Engineering, Machine Learning, Portfolio"

# # Footer Configuration
footer_text: "© 2024 Chaitanya Devarshi. All rights reserved!"
