title: Chaitanya Devarshi
logo: assests/img/imagee.png
# description: text below image
show_downloads: true
theme: jekyll-theme-minimal
social_links:
  linkedin: https://www.linkedin.com/in/chaitanya-devarshi-7339261b1/
